name: Test EC2 GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  create-ec2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run terraform init
        run: |
          terraform init
          terraform apply -auto-approve
        working-directory: ./aws
        shell: bash
